### ISSUE TITLE
Possible issues to keep in mind.

### ISSUE THREAD

**Issue by Nemirtingas** [acidicoala/ScreamAPI#1]
https://github.com/acidicoala/ScreamAPI/blob/master/Overlay/src/Overlay.cpp#L65
The main Window that runs the Even Loop is not always the Window that is used for rendering. (Already faced that on the Steam Overlay).

https://github.com/acidicoala/ScreamAPI/blob/master/Overlay/src/Overlay.cpp#L94
I believe that the overlay only supports DX11 then ? Maybe you should add a comment in the readme about only DX11 support.

https://github.com/acidicoala/ScreamAPI/blob/master/Overlay/src/kiero/kiero.cpp#L637-L664
D3D9 is sometimes already loaded even if not used. You should keep this info in mind if you plan to support multiple versions of DX. You should maybe reverse the DX auto discovery, DX12, DX11, DX10 and finally DX9.

**Comment by acidicoala** [comment]
> The main Window that runs the Even Loop is not always the Window that is used for rendering. (Already faced that on the Steam Overlay).

That's interesting. Could you elaborate a bit more on this point and under which scenarios it occurs?
#
> I believe that the overlay only supports DX11 then ? Maybe you should add a comment in the readme about only DX11 support.

Yes, for now it supports only DX11 because I only had a chance to test it with DX11. I have specified it both in the GitHub release notes and in the topic header.

#
> D3D9 is sometimes already loaded even if not used. You should keep this info in mind if you plan to support multiple versions of DX. You should maybe reverse the DX auto discovery, DX12, DX11, DX10 and finally DX9.

I did not even know of the auto-discovery feature present in kiero, thanks for bringing it up as well. I'm thinking of implementing my own renderer auto-discovery (with your suggested order) later on, because I would also need to change ImGui initialization method calls based on the discovered renderer.
### Notes about DX versions

I know only of 3 games that use EOS achievements: Remnant: FtA, MW5 & Ark: SE. As far as I know, all of them use DX11, except for Ark which also supports DX10. Given this state of affairs I don't think there will be a need to include previous DX versions. But I am looking forward to implementing support for DX12 & Vulcan if Epic gives away some games that use those renderers and use EOS achievements.

**Comment by Nemirtingas** [comment]
Ok, didn't see the DX11 support only message. My bad.

About the main Window, it really depends on the game. I don't know if any EPIC game has this issue but here's the code that I tries to fix the event loop issue: https://gitlab.com/Nemirtingas/goldberg_emulator/-/blob/6aefb71c321ada645c78fc483c29b8e26179a09f/overlay_experimental/windows/Windows_Hook.cpp#L48-65

Civilisation 6 also use achievements and supports DX12.

**Comment by acidicoala** [comment]
> bout the main Window, it really depends on the game. I don't know if any EPIC game has this issue but here's the code that I tries to fix the event loop issue: https://gitlab.com/Nemirtingas/goldberg_emulator/-/blob/6aefb71c321ada645c78fc483c29b8e26179a09f/overlay_experimental/windows/Windows_Hook.cpp#L48-65

Ok, I will definitely consult it if I run into this issue with any Epic game that uses achievements.

> Civilisation 6 also use achievements and supports DX12.
Now that is really surprising. Last time I had Civ 6 installed it had no such feature. Have they added it recently?

**Comment by Nemirtingas** [comment]
I don't think thats new, they might not show it, but they have uploaded achievements and you can see them while playing the game, it loads the achievements definitions.

**Comment by acidicoala** [comment]
Did they also had overlay?

**Comment by Nemirtingas** [comment]
> 
> 
> Did they also had overlay?

No idea, I try to dump as much things as I can from EPIC. The EpicData website will be abandoned by its maintainer (saw it on the Discord channel). I don't know if we can dump achievements and leaderboards from their webapi so I just insert my EOS dll and generate everything I can. I've created a github repo for that: https://github.com/Nemirtingas/epic_games_infos.
I dump games/dlc appids with a modified "legendary".

**Comment by acidicoala** [comment]
Damn, sad to hear about the EpicData abandonment. Although I was actually surprised that it worked somehow for a period of time, given that their REST API is exposed through Arkose Labs. I couldn't get any rest api calls working reliably...

**Comment by Nemirtingas** [comment]
I'm building a simple file sharing website for steam & epic datas. You can find Civilisation 6 achivements here (using TOR): http://ginfos4qviyrkfc55garcuvszbryj5ubfal7btls763fvp4jvpmyy4qd.onion/ep/Kinglet/
