### ISSUE TITLE
Unknown file version error? 

### ISSUE THREAD

**Issue by Coffe2Go** [acidicoala/ScreamAPI#8]
[https://prnt.sc/v836vy](url)

The game has the DLL in binaries as 64Bit etc....  not sure why its not working might be due to EasyAntiCheat?

**Comment by acidicoala** [comment]
Yes, that's what any serious anti-cheat is for, to prevent tampering with game binaries. In some games it is possible to disable anti-cheat but that typically means that online features won't be available. Regardless of whether or not this is possible, there is nothing that can be done from the ScreamAPI side. Instead you should read through the [respective game topic](https://cs.rin.ru/forum/viewtopic.php?f=38&t=102550&hilit=predator), since your issue is specific to that game.

**_P.S._ Don't abuse the Google Sheets feature of requesting edit access in order to ask for something. It's not cool and will never work. Instead seek help in the appropriate game topic, that I have linked above. Same goes to the notes section of the compatibility sheet.**

**Comment by Coffe2Go** [comment]
Huh interesting been reading about how even for some people the games work with anti cheats... but then again i have 0 knowledge lol...  But then again guess im unlucky in that case haha...

Yeah my apologies i thought its sort of like a "requesting/feedback" type of stuff... i read community as in "feel free to request game support"

**Comment by acidicoala** [comment]
> i read community as in "feel free to request game support"

It is a place to share your test results, so that other people might find it useful. If you have further questions feel free to continue in the forum, and keep in mind the forum rules as well.
